version: "3.7"
volumes:
  db-store:
  php-fpm-socket:
  vendor-volume:
  storage-volume:

services: 
  web:
    container_name: ${APP_NAME}_nginx
    build: ./docker/nginx
    ports:
      - ${NGINX_PORT}:80
    volumes: 
      - ./${APP_NAME}/public:/var/www/html/${APP_NAME}/public
      - ./docker/nginx/templates:/etc/nginx/templates
      - ./docker/nginx/conf.d:/etc/nginx/conf.d/
      - php-fpm-socket:/var/run
    environment: 
      - APP_NAME=${APP_NAME}
    command: /bin/ash -c "envsubst '$$APP_NAME' < /etc/nginx/templates/default.conf.template > /etc/nginx/conf.d/default.conf && nginx -g 'daemon off;'"
    depends_on: 
      - app
      - mysql
  
  app:
    container_name: ${APP_NAME}_app
    build: ./docker/php
    working_dir: /var/www/html/${APP_NAME}
    environment: 
      - APP_NAME=${APP_NAME}
      - DB_CONNECTION=mysql
      - DB_HOST=mysql
      - DB_DATABASE=${DB_NAME}
      - DB_USERNAME=${DB_USER}
      - DB_PASSWORD=${DB_PASS}
      - TZ=${TZ}
    volumes: 
      - ./${APP_NAME}:/var/www/html/${APP_NAME}
      - vendor-volume:/var/www/html/${APP_NAME}/vendor
      - storage-volume:/var/www/html/${APP_NAME}/storage
      - ./docker/php/php_fpm/php-fpm.d/zz-docker.conf:/usr/local/etc/php-fpm.d/zz-docker.conf
      - php-fpm-socket:/var/run
  
  node:
    container_name: ${APP_NAME}_node
    image: node:12.14-alpine
    tty: true
    working_dir: /work/application
    volumes: 
      - ./${APP_NAME}:/work
  
  mysql:
    container_name: ${APP_NAME}_mysql
    image: mysql:5.7
    ports:
      - ${DB_PORT}:3306
    environment: 
      - MYSQL_DATABASE=${DB_NAME}
      - MYSQL_USER=${DB_USER}
      - MYSQL_PASSWORD=${DB_PASS}
      - MYSQL_ROOT_PASSWORD=${DB_PASS}
      - TZ=${TZ}
    volumes: 
      - db-store:/var/lib/mysql
