version: "3.7"
volumes:
  db-store:
  php-fpm-socket:
  vendor-volume:
  storage-volume:

services: 
  web:
    container_name: ${APP_GROUP}_nginx
    build: ./docker/nginx
    ports:
      - ${NGINX_PORT}:80
    volumes: 
      - ./laravel/application/public/index.php:/var/www/html/application/public/index.php
      - ./docker/nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./docker/nginx/conf.d:/etc/nginx/conf.d/
      - php-fpm-socket:/var/run
    depends_on: 
      - app
      - mysql
  
  app:
    container_name: ${APP_GROUP}_app
    build: ./docker/php
    working_dir: /var/www/html/application
    environment: 
      - DB_CONNECTION=mysql
      - DB_HOST=mysql
      - DB_DATABASE=${DB_NAME}
      - DB_USERNAME=${DB_USER}
      - DB_PASSWORD=${DB_PASS}
      - TZ=${TZ}
    volumes: 
      - ./laravel:/var/www/html/
      - vendor-volume:/var/www/html/application/vendor
      - storage-volume:/var/www/html/application/storage
      - ./docker/php/php_fpm/php-fpm.d/zz-docker.conf:/usr/local/etc/php-fpm.d/zz-docker.conf
      - php-fpm-socket:/var/run
  
  node:
    container_name: ${APP_GROUP}_node
    image: node:12.14-alpine
    tty: true
    working_dir: /work/application
    volumes: 
      - ./laravel:/work
  
  mysql:
    container_name: ${APP_GROUP}_mysql
    image: mysql:5.7
    ports:
      - ${DB_PORT}:3306
    environment: 
      - MYSQL_DATABASE=${DB_NAME}
      - MYSQL_USER=${DB_USER}
      - MYSQL_PASSWORD=${DB_PASS}
      - MYSQL_ROOT_PASSWORD=${DB_PASS}
      - TZ=${TZ}
    volumes: 
      - db-store:/var/lib/mysql
